### ISSUE TITLE
Training hangs at “Synchronizing parameters for rank 0...” when using multiple GPUs

### ISSUE THREAD

**Issue by sunpihai-up** [Hellod035/LeggedLab#44]
Hello, I’m encountering a problem when attempting to run training with multiple GPUs. The process consistently gets stuck at the following message and never progresses:

```
Synchronizing parameters for rank 0...
```

The command I use to launch training is:

```
python legged_lab/scripts/train.py --task=g1_flat --headless --logger=tensorboard --num_envs=4096
```

This only happens when multiple GPUs are involved; single-GPU training works normally.

I’d like to ask if anyone else has experienced this behavior or has suggestions on how to resolve it. Thank you!

**Comment by sunpihai-up** [comment]
I solved the problem.
```python
if args_cli.distributed:
    # Add this line in train.py
    env_cfg.device = f"cuda:{app_launcher.local_rank}"
    env_cfg.sim.device = f"cuda:{app_launcher.local_rank}"
    agent_cfg.device = f"cuda:{app_launcher.local_rank}"

    # set seed to have diversity in different threads
    seed = agent_cfg.seed + app_launcher.local_rank
    env_cfg.scene.seed = seed
    agent_cfg.seed = seed
```
